server:
  port: 9999

#rabbitmq
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    apiport: 15672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        #消费者数量
        concurrency: 10
        max-concurrency: 10
        #消费者每次从队列获取的消息数量
        prefetch: 1
        #消费者自动启动
        auto-startup: true
        #消息失败，自动重新入队
        default-requeue-rejected: true
    template:
      #启用发送重试
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 3
        max-interval: 10000
        multiplier: 1.0
#  thymeleaf:
#    cache: false
#    mode: html
#    encoding: UTF-8
#    servlet:
#      content-type: text/html

#设置静态资源路径，多个以逗号分隔,spring-boot 对Thymeleaf很多配置有默认配置，如默认页面映射路径为： classpath:/templates/， 默认的文件后缀为： .html。
spring.resources.static-locations: classpath:static/,file:static/